matrix:
  include:
    - language: php
      php: 7.4
    - name: "PHP: 7.4"
      language: sh
      os: windows
      before_install:
        - choco install php --package-parameters='"/InstallDir:C:\php"'
        - export PATH=/c/php:$PATH
        - wget http://getcomposer.org/composer.phar
        - php composer.phar install

# faster builds on new travis setup not using sudo
sudo: false

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache

install:
  - travis_retry composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install --prefer-dist --no-interaction

script:
  - |
    vendor/bin/phpunit $PHPUNIT_FLAGS --coverage-clover=coverage.clover

after_script:
  - wget -c https://scrutinizer-ci.com/ocular.phar
  - php php-ocular code-coverage:upload --format=php-clover coverage.clover
