matrix:
  include:
    - language: php
      php: 7.4
    - name: "PHP: 7.4"
      language: sh
      os: windows
      before_install:
        - choco install php --package-parameters='"/InstallDir:C:\php"'
        - sed -i 's/;extension=openssl/extension=openssl/g' /c/php/php.ini
        - sed -i 's/;extension=mbstring/extension=mbstring/g' /c/php/php.ini
        - export PATH=/c/php:$PATH
        - choco install composer --ia '"/DEV=C:\tools\php /PHP=C:\php"'
        - export PATH=/c/tools/php:$PATH
        - mkdir -p /c/php/ext/xdebug
        - wget -P /c/php/ext/xdebug 'https://xdebug.org/files/php_xdebug-2.9.4-7.4-vc15-nts-x86_64.dll'
        - echo 'zend_extension="C:\php\ext\xdebug\php_xdebug-2.9.4-7.4-vc15-nts-x86_64.dll"' >> /c/php/php.ini

# faster builds on new travis setup not using sudo
sudo: false

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache

install:
  - travis_retry composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install --prefer-dist --no-interaction

script:
  - |
    vendor/bin/phpunit $PHPUNIT_FLAGS --coverage-clover=coverage.clover

after_script:
  - wget -c https://scrutinizer-ci.com/ocular.phar
  - php php-ocular code-coverage:upload --format=php-clover coverage.clover
